#
# Copyright (c) Icanio
#

server.port=8081
spring.jpa.database=POSTGRESQL
spring.datasource.url=jdbc:postgresql://localhost:5432/veruna
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.main.banner-mode=off
spring.main.log-startup-info=false
spring.jpa.generate-ddl=true
spring.jpa.show-sql=false

# Swagger Configuration
springdoc.swagger-ui.path=/swagger-ui.html







#
#salesforce.username=rajaselvamala.a-ulth@force.com
#salesforce.password=Password123jV2pgsEpSzff11eclQ5kdPj2q
#salesforce.securityToken=00DdN00000EFbTq!AQEAQGCKRUtx08UtlL04vkVDAiYObOFh8ixMjA.ZSnS3i1cbFUEr5zEBtauEEvcGARmXGhca4g7mktHS54E5JPQwoSFNRBEp
#salesforce.clientId=3MVG9GBhY6wQjl2uQfPOOhtp9bDqlgKYfOecsFsd8sjP3otWQWvTXuODReUx.a5Aw9kT9UbtEd1cahhS5o1W3
#salesforce.clientSecret=F329D25336EB612C362979BD068B7030579FD5D5D22666172D789BEAD2C08F60
#
#
##salesforce.authEndpoint=https://page-energy-6644.lightning.force.com/lightning/setup/AddUsers/home
#
#
##salesforce.authEndpoint=https://page-energy-6644.my.salesforce.com/services/Soap/u/53.0
#
#salesforce.authEndpoint=https://login.salesforce.com/services/Soap/u/50.0
#
#
#salesforce.api-endpoint=https://page-energy-6644.my.salesforce.com/services/data/v53.0/sobjects/User
#
#









#salesforce.username=rajaselvamala.a-ulth@force.com
#salesforce.username=jebastin.prabaharan@ideas2it.vrna.com
#salesforce.username=sivakamisowmiya.khhqr@force.com
salesforce.username=rajaselvamala.a@cunning-otter-7f39g7.com



#salesforce.password=Password123jV2pgsEpSzff11eclQ5kdPj2q
#salesforce.password=Ideas2IT2024vGlfbqIQhJgxNvvD7KG0Ch9UQ
#salesforce.password=Shmily%4546ZR5VJFUdYwcwyyRh6mXbnr6k
salesforce.password=Password1238hCRjPAN5SgepHrm3f88yZrc



salesforce.securityToken=00DdL00000AlOZ0!AQEAQECA60CHuTGZ.zGykMObhptjZ_2di9GtaluF1o3Zk55gUNEugTmnOVfKidyIqx16EXpSgEevWHcpiX3wIg834DZICXEo



#salesforce.clientId=3MVG9GBhY6wQjl2uQfPOOhtp9bDqlgKYfOecsFsd8sjP3otWQWvTXuODReUx.a5Aw9kT9UbtEd1cahhS5o1W3
#salesforce.clientId=3MVG9wfACBgtCq9GRV4xhFgWyn_rFUQP6OWeZ9o7fV6JjOYf.j_Hi0p4gjTFhBBKPkuu_StT8h4LpR7Wa5QWz
#salesforce.clientId=3MVG9bZIBBVRES4EoUUvMxBH054ts5ofgYCN1iSfOZAxq8KeJXOpOKls2VsXUog3lX6ruDDz4i0NH1sIS4H2T
salesforce.clientId=3MVG9GCMQoQ6rpzSrxABSBavVxnBHgxZkjwdpqKDwOIOzNHNdWKbWLc4lCwGb.doFLEgka4YqFB55UExH415w


#salesforce.clientSecret=F329D25336EB612C362979BD068B7030579FD5D5D22666172D789BEAD2C08F60
#salesforce.clientSecret=F673DB6A4E3C918395D9FB8509EBE6ED19289D545C1A2867006FEA538807F67C
#salesforce.clientSecret=05F7E388B91891FE599A71B53CCBBC4D79D5D5019F4B72D59D0048CA334D6BA3
salesforce.clientSecret=9C780C371799E67803423EB946F758A8FD17FEFBED3E76A60668BF94C6215360



salesforce.authEndpoint=https://cunning-otter-7f39g7-dev-ed.trailblaze.my.salesforce.com/services/oauth2/token



salesforce.api-endpoint=https://cunning-otter-7f39g7-dev-ed.trailblaze.my.salesforce.com/services/data/v53.0/sobjects/User