spring.application.name=SpringBasics

spring.datasource.url=jdbc:postgresql://localhost:5432/springboot
spring.datasource.username=postgres
spring.datasource.password=root

# Spring Boot will use this driver to connect to the PostgreSQL database.
spring.datasource.driver-class-name=org.postgresql.Driver
# Controls how and when Spring Boot will initialize the data source.
# Always initialize the data source
spring.datasource.initialization-mode=always
# Hibernate dialect for PostgreSQL
# The dialect helps Hibernate generate SQL that is compatible with PostgreSQL.
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Update schema automatically
spring.jpa.hibernate.ddl-auto=update
# Disable SQL query logging
spring.jpa.show-sql=false


spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your-email@gmail.com
spring.mail.password=your-app-password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



#Completely Disable the Banner
#spring.main.banner-mode=off
